### ISSUE TITLE
[https/main] https로 도메인네임 적용해서 배포

### ISSUE THREAD

**Issue by junsu1220** [moodCatcherProject/Front-End#44]
# 0911
- route53 이용 DNS 적용
- CloudFront 이용 SSL 인증서를 이용한 HTTPS 호스팅을 지원
- ACM을 이용하여 인증서를 받은 후 Elastic Load Balancer, Amazon CloudFront 배포

**Comment by crystal025** [comment]
- 도메인 구입 및 레코드 설정
<img width="409" alt="스크린샷 2022-09-11 오후 11 13 10" src="https://user-images.githubusercontent.com/109053875/189532222-25c01a96-0ac1-4ec5-ad0d-8af22650c2f4.png">
- ACM으로 SSL(인증서)등록
<img width="1098" alt="스크린샷 2022-09-11 오후 11 18 23" src="https://user-images.githubusercontent.com/109053875/189532423-750c4521-b053-49c4-8eb0-b75a9d2a5f86.png">
- CloudFront에서 htttps 적용
<img width="1068" alt="스크린샷 2022-09-11 오후 11 19 35" src="https://user-images.githubusercontent.com/109053875/189532515-2e1b316a-8ca5-42c5-9a39-99840c315eb0.png">

**Comment by junsu1220** [comment]
- 추가적으로 버킷을 새로 만들어야합니다.(버킷이름을 도메인이름과 같게 해야함)
  - 관련 링크 -> https://heo-dev-0229.tistory.com/35?category=931800
- 새로 만든 버킷과 github actions를 연결해야합니다.
- 백엔드 서버와 https 통신을 주고받는지 확인해야합니다.

**Comment by junsu1220** [comment]
### 09/12
---
- s3버킷을 새로 만들었습니다.(버킷의 이름은 DNS와 같게 설정)
- 깃허브액션의 시크릿 부분의 서버주소를 https로 바꾸었습니다.
- 기존의 route 53의 레코드를 삭제하고 -> 새롭게 클라우드 프론트를 만든 후에(새로운 버킷과 연결하여) -> 다시 route53의 레코드를 클라우드프론트와 연결했습니다.
- https, 서버와의 통신, env처리 완료
